before_script:
  # tomb and pass dependencies
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install --no-install-recommends -y git tree zsh sudo gnupg cryptsetup pinentry-curses gawk  libgcrypt20-dev steghide qrencode e2fsprogs shellcheck dcfldd steghide qrencode
  - sudo swapoff -a

  # Installing password-store
  - git clone https://git.zx2c4.com/password-store
  - sudo make --directory=password-store install

  # Installing tomb
  - git clone https://github.com/dyne/Tomb.git
  - sudo make --directory=Tomb install

stages:
  - test

test:
  stage: test
  script:
    - chmod 744 tests/runtests
    - chmod 744 tomb.bash open.bash close.bash
    - make test
